using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace PutIo.Sharp.Models.Shared
{
    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum SubtitleLanguage
    {
        [EnumMember(Value = "afr")] Afrikaans,
        [EnumMember(Value = "alb")] Albanian,
        [EnumMember(Value = "ara")] Arabic,
        [EnumMember(Value = "arm")] Armenian,
        [EnumMember(Value = "baq")] Basque,
        [EnumMember(Value = "bel")] Belarusian,
        [EnumMember(Value = "ben")] Bengali,
        [EnumMember(Value = "bos")] Bosnian,
        [EnumMember(Value = "bre")] Breton,
        [EnumMember(Value = "bul")] Bulgarian,
        [EnumMember(Value = "bur")] Burmese,
        [EnumMember(Value = "cat")] Catalan,
        [EnumMember(Value = "chi")] Chinese_Simplified,
        [EnumMember(Value = "zho")] Chinese_traditional,
        [EnumMember(Value = "hrv")] Croatian,
        [EnumMember(Value = "cze")] Czech,
        [EnumMember(Value = "dan")] Danish,
        [EnumMember(Value = "dut")] Dutch,
        [EnumMember(Value = "eng")] English,
        [EnumMember(Value = "epo")] Esperanto,
        [EnumMember(Value = "est")] Estonian,
        [EnumMember(Value = "fin")] Finnish,
        [EnumMember(Value = "fra")] French,
        [EnumMember(Value = "glg")] Galician,
        [EnumMember(Value = "geo")] Georgian,
        [EnumMember(Value = "ger")] German,
        [EnumMember(Value = "gre")] Greek,
        [EnumMember(Value = "heb")] Hebrew,
        [EnumMember(Value = "hin")] Hindi,
        [EnumMember(Value = "hun")] Hungarian,
        [EnumMember(Value = "ice")] Icelandic,
        [EnumMember(Value = "ind")] Indonesian,
        [EnumMember(Value = "ita")] Italian,
        [EnumMember(Value = "jpn")] Japanese,
        [EnumMember(Value = "kaz")] Kazakh,
        [EnumMember(Value = "khm")] Khmer,
        [EnumMember(Value = "kor")] Korean,
        [EnumMember(Value = "lav")] Latvian,
        [EnumMember(Value = "lit")] Lithuanian,
        [EnumMember(Value = "ltz")] Luxembourgish,
        [EnumMember(Value = "mac")] Macedonian,
        [EnumMember(Value = "may")] Malay,
        [EnumMember(Value = "mal")] Malayalam,
        [EnumMember(Value = "mni")] Manipuri,
        [EnumMember(Value = "mon")] Mongolian,
        [EnumMember(Value = "nor")] Norwegian,
        [EnumMember(Value = "oci")] Occitan,
        [EnumMember(Value = "per")] Persian,
        [EnumMember(Value = "pol")] Polish,
        [EnumMember(Value = "por")] Portuguese,
        [EnumMember(Value = "pob")] Portuguese_Brazil,
        [EnumMember(Value = "rum")] Romanian,
        [EnumMember(Value = "rus")] Russian,
        [EnumMember(Value = "srp")] Serbian,
        [EnumMember(Value = "sin")] Sinhalese,
        [EnumMember(Value = "slo")] Slovak,
        [EnumMember(Value = "slv")] Slovenian,
        [EnumMember(Value = "spa")] Spanish,
        [EnumMember(Value = "swa")] Swahili,
        [EnumMember(Value = "swe")] Swedish,
        [EnumMember(Value = "syr")] Syriac,
        [EnumMember(Value = "tgl")] Tagalog,
        [EnumMember(Value = "tam")] Tamil,
        [EnumMember(Value = "tel")] Telugu,
        [EnumMember(Value = "tha")] Thai,
        [EnumMember(Value = "tur")] Turkish,
        [EnumMember(Value = "ukr")] Ukrainian,
        [EnumMember(Value = "urd")] Urdu,
        [EnumMember(Value = "vie")] Vietnamese,
    }
}